server:
 port: 2000
 servlet:
    context-path: /treinamento
 
spring:
  application:
    name: "treinamento"
  datasource:
    url: jdbc:postgresql://localhost:5432/treinamento
    username: postgres
    password: postgres
    driver: 
      class: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:/db/dbchangeLog.xml
  jpa:
    hibernate:
      ddl-auto: none